services:
  api:
    build:
      context: .
    restart: no
    command: sh run.sh
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      - ./:/app
      - gradle:/home/spring/.gradle
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
        - database

  database:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - dgp:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  gradle:
  dgp:
    driver: local
