services:
  api:
    build:
      context: .
    restart: no
    command: sh run.sh
    ports:
      - "8080:8080"
    expose:
      - 8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/app
      - gradle:/home/spring/.gradle
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
    depends_on:
        - database

  database:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - dgp:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  gradle:
  dgp:
    driver: local

networks:
  frontend:
