spring:
  banner:
    location: classpath:banner.txt
  application:
    name: DGP
  data:
    rest:
      base-path: /
  jpa:
    hibernate:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://database:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db-changelog.yaml
